In [10]:
from PIL import Image
import imageio
import numpy as np
import xml

In [13]:
#img = imageio.imread('ch2_ohr_nrp_20200229T0938004033_d_img_d32/browse/raw/20200229/ch2_ohr_nrp_20200229T0938004033_b_brw_d32.png')
img = Image.open('ch2_ohr_nrp_20200229T0938004033_d_img_d32/browse/raw/20200229/ch2_ohr_nrp_20200229T0938004033_b_brw_d32.png')
#print(img)
img = np.array(img)
print(img)
print(img.shape)

[[134 137 174 ... 194 199 183]
 [176 155  53 ... 186 178 175]
 [206 201 154 ... 207 173 173]
 ...
 [145 118  90 ... 103 142 129]
 [106 117  61 ... 125  55 158]
 [ 92 186 136 ... 113 130 105]]
(9369, 1200)


In [19]:
f = open('ch2_ohr_nrp_20200229T0938004033_d_img_d32/miscellaneous/readme.txt','r')
file = f.read()
n = file.find("Latitude of OHRC payload trace")
print(file[n:n+len("Latitude of OHRC payload trace")])

Latitude of OHRC payload trace


In [6]:
f = open("DataSet/TMC/ch2_tmc_ndn_20230223T1106344149_d_oth_n18/data/derived/20230223/ch2_tmc_ndn_20230223T1106344149_d_oth_n18.xml",'r')
print(f.read())

OSError: [Errno 22] Invalid argument: 'DataSet/TMC/ch2_tmc_ndn_20230223T1106344149_d_oth_n18/data/derived/20230223/ch2_tmc_ndn_20230223T1106344149_d_oth_n18.xml'